### ISSUE TITLE
Unable to print all records

### ISSUE THREAD

**Issue by alishanvr** [shabihhaider/Gender-Prognosis-Guess-the-Gender-of-a-person-#1]
I am unable to print all records by default. 
Secondly, remove the highlighted portions in PDF/printing. 

![AliShanScreenshot 2024-08-02 at 5  54 35@2x](https://github.com/user-attachments/assets/8a2ed1d7-006a-45f2-b995-914edcef36aa)

**Comment by shabihhaider** [comment]
I solved this issue. Please check. #1
