### ISSUE TITLE
Menu issue on Login page

### ISSUE THREAD

**Issue by alishanvr** [shabihhaider/Gender-Prognosis-Guess-the-Gender-of-a-person-#3]
I am already logged in and on the login page, I can see a Sign Up and Logout button. That is not correct. 

![AliShanScreenshot 2024-08-02 at 6  00 05@2x](https://github.com/user-attachments/assets/cbc909c2-6b43-4d12-b241-95e7092b415f)

Sign up button should only available when user is not logged in. Same with the logout button. Logout button only available if user is  logged in.

**Comment by shabihhaider** [comment]
This is resolved.
