### ISSUE TITLE
Test - remove restriction

### ISSUE THREAD

**Issue by alishanvr** [shabihhaider/Gender-Prognosis-Guess-the-Gender-of-a-person-#4]
We need to test the following case:

> If user is logged in then remove the 10 minutes wait. (This mean the logged in user can use without any limit).

Please share a video with me for this point. Use loom to record video.

**Comment by shabihhaider** [comment]
https://github.com/user-attachments/assets/35d8660d-ae7b-45cc-a36a-eed208ab8b49


https://github.com/user-attachments/assets/410c9ab8-4f1a-4ea6-af20-38c3cac2bfbc


https://github.com/user-attachments/assets/68a92784-31e1-436f-ac7b-1712cfd3c889

When a user is logged in, it can search limitlessly; when not logged in, it will wait after 3 searches for 10 minutes.
