### ISSUE TITLE
Remove all or anyone record

### ISSUE THREAD

**Issue by alishanvr** [shabihhaider/Gender-Prognosis-Guess-the-Gender-of-a-person-#5]
I added the following point to complete. But still not completed. 

> add remove functionality. (User can remove any one record or all record at once).

**Comment by shabihhaider** [comment]
This is the video that is manifest that you can Remove all records or anyone at once.

https://github.com/user-attachments/assets/785f6de8-2101-4cc9-ba12-1e5f40e92641
