### ISSUE TITLE
Redirect user and continue their journey

### ISSUE THREAD

**Issue by alishanvr** [shabihhaider/Gender-Prognosis-Guess-the-Gender-of-a-person-#7]
We need to redirect the user's journey without breaking. 
I already created this point but still not developed. 

> This is only accessible if user is logged in. If user is not logged in then redirect them to login page. And once login then again redirect to history page (Only if they requested for the history page).

Please ask any questions that you may have.

**Comment by shabihhaider** [comment]
https://github.com/user-attachments/assets/c7250da3-86ea-4db5-9d25-351990d463ff
